% bf_TEST: bushfire TEST batch file 
% MODULE:
%   drought_fire
% NAME:
%   bf_TEST_simple
% PURPOSE:
%   TEST bushfire module
%   
%   Uses TEST data within the module's data folder (and subfolders). For
%   operational use, use the standard climada data folder (see
%   climada_global.data_dir), i.e. copy centroids, entities etc. to the
%   respective sub-folders there.
%
%   please refer to the main code climada_bf_hazard_set
% CALLING SEQUENCE:
%   bf_TEST_simple
% EXAMPLE:
%   bf_TEST_simple
% INPUTS:
% OPTIONAL INPUT PARAMETERS:
% OUTPUTS:
% MODIFICATION HISTORY:
% Roxanne Doerge, Dina Haenseler, Elisabeth Tschumi, 20170609, initial, key author
%-

global climada_global
if ~climada_init_vars,return;end % init/import global variables

%% Import global variables
% init/import global variables
% close all; clear all; clc
% cd climada_global.root_dir
%
% Please locate to your climada-master folder.
%startup;

%% Parameters
%
% find the local path to the module
module_data_dir=[fileparts(fileparts(which('bf_TEST_simple'))) filesep 'data'];
%
% define the path and filename of the intermediate step data file
bf_file=[module_data_dir filesep 'hazards' filesep 'external_model_output' filesep 'ZAF_BF_proto_data.mat'];
% This file was generated by with bf_generator_jumpy. To learn how to
% generate such a set, please read the introduction in bf_generator_jumpy.m

% define the path and filename of the centroids file
centroids_file = [module_data_dir filesep 'centroids' filesep 'ZAF_bf_centroids.mat'];

% define the path and filename of the entities file
entity_today_file=[module_data_dir filesep 'entities' filesep 'entity_ZAF.mat'];


if ~exist(bf_file,'file')
    [fP,fN]=fileparts(bf_file);
    fprintf('ERROR: %s not found\n',bf_file)
    fprintf('-> please locate intermediate step data file %s (run bf_generator_jumpy)\n',fN)
    return
else
    load(bf_file)
end

if ~exist(centroids_file,'file')
    [fP,fN]=fileparts(centroids_file);
        fprintf('ERROR: %s not found\n',centroids_file)
    fprintf('-> please locate the centroids file %s, edit %m\n',fN)
    return
else
    load(centroids_file)
end

if ~exist(entity_today_file,'file')
    [fP,fN]=fileparts(entity_today_file);
        fprintf('ERROR: %s not found\n',entity_today_file)
    fprintf('-> please locate the entity file %s, edit %m\n',fN)
    return
end

%% Generate Hazard Sets and plot entities

% generate the hazard sets (_ in filename to easily find them)
hazard_today        = climada_bf_hazard_set(bf,centroids,1.00,'','_TEST_ZAF_SouthAfrica_BF_today');
hazard_CC_f3        = climada_bf_hazard_set(bf,centroids,1.03,'','_TEST_ZAF_SouthAfrica_BF_CC_f3');
hazard_CC_f65       = climada_bf_hazard_set(bf,centroids,1.65,'','_TEST_ZAF_SouthAfrica_BF_CC_f65');

% read and encode the entities
entity_today = climada_entity_read(entity_today_file,hazard_today);
entity_2030 = entity_today;
entity_2030.assets.Value = entity_today.assets.Value*1.32;     
entity_2030.assets.Cover = entity_2030.assets.Value;

% plot entities
figure
climada_map_plot(entity_today)

%% Plot fires
clear i;
n=length(bf);
figure
for i=1:n
    scatter(bf(i).lon,bf(i).lat,30,bf(i).intensity,'filled','s'); colormap hot;
    hold on
end
climada_plot_world_borders(2);
    xlim([15,38]); % ZAF    %xlim([143,147]);
    ylim([-37,-22]); % ZAF  %ylim([-38,-34]);
    xlabel('longitude')
    ylabel('latitude')
    grid on
    legend('simulated fires','location','southeast')
    
% Please zoom in to see smaller scale structure of the fires.
    
%% Generate Hazard Sets and Risk Plot

% calculate risk today, + ecnomic development, + low/high climate change (CC)
EDS_today = climada_EDS_calc(entity_today,hazard_today);
EDS_2030 = climada_EDS_calc(entity_2030,hazard_today);
EDS_2030_CC_f3 = climada_EDS_calc(entity_2030,hazard_CC_f3);
EDS_2030_CC_f65 = climada_EDS_calc(entity_2030,hazard_CC_f65);

% plot risk for high and low climate change scenario
figure
subplot(1,2,1);climada_waterfall_graph(EDS_today,EDS_2030,EDS_2030_CC_f3); title('low climate change')
subplot(1,2,2);climada_waterfall_graph(EDS_today,EDS_2030,EDS_2030_CC_f65);title('high climate change')

%% Adaptation

% establish baseline today
res_today_adapt = climada_measures_impact(entity_today,hazard_today,'no');

% impact of fire fighters
diff_AED_ff = res_today_adapt.ED(end)-res_today_adapt.ED(1);
% impact of education
diff_AED_edu = res_today_adapt.ED(end)-res_today_adapt.ED(2);
% impact of sprinkler system
diff_AED_sprinkler = res_today_adapt.ED(end)-res_today_adapt.ED(3);

res_2030_adapt_CC_f3  = climada_measures_impact(entity_2030, hazard_CC_f3, res_today_adapt);
res_2030_adapt_CC_f65 = climada_measures_impact(entity_2030, hazard_CC_f65,res_today_adapt);

% for it to work needed to comment out row 324 in
% climada_adaptation_cost_curve.m: clear clear measures_impact_comparison
figure
subplot(1,1,1);climada_adaptation_cost_curve(res_2030_adapt_CC_f3,res_2030_adapt_CC_f65)