% bf_TEST_jumpy: combined bushfire TEST batch file
% MODULE:
%   drought_fire
% NAME:
%   bf_TEST_jumpy
% PURPOSE:
%   TEST combined bushfire module, base don FIRMS data an cellular automat
%
%   Uses TEST data within the module's data folder (and subfolders). For
%   operational use, use the standard climada data folder (see
%   climada_global.data_dir), i.e. store your FIRMS data in
%   ../hazards/external_model_output etc.
%
%   please refer to the main code bf_generator_jumpy and climada_bf_hazard_set
% CALLING SEQUENCE:
%   bf_TEST_jumpy
% EXAMPLE:
%   bf_TEST_jumpy
% INPUTS:
%   none, it's a batch job, see PARAMETERS. --> To run the whole TEST for
%   another country, you should only have to change country_ISO3_code and csv_file.
% OPTIONAL INPUT PARAMETERS:
% OUTPUTS:
% MODIFICATION HISTORY:
% doerger@student.ethz.ch,dinah@student.ethz.ch,tschumie@student.ethz.ch,20170609, initial, based on bf_TEST
% david.bresch@gmail.com, 20170623, climada-compatibility
%-

global climada_global
if ~climada_init_vars,return;end % init/import global variables

module_data_dir=[fileparts(fileparts(which('bf_TEST_jumpy'))) filesep 'data']; % local path to the module

% PARAMETERS
%
% to run the whole TEST for another country, you should only have to change
% the ISO3 code and csv_file:
%country_ISO3_code='ZAF';
country_ISO3_code='ESP';
%csv_file = [module_data_dir filesep 'hazards' filesep 'external_model_output' filesep 'fire_archive_M6_11367.csv'];
%csv_file = [module_data_dir filesep 'hazards' filesep 'external_model_output' filesep 'fire_nrt_M6_ZAF_april.csv'];
csv_file = [module_data_dir filesep 'hazards' filesep 'external_model_output' filesep 'ESP_fire_archive_M6_13387.csv'];
%
plot_fires=0; % as this takes time, you csan set =0
%
[country_name,country_ISO3_code]=climada_country_name(country_ISO3_code); % to check
country_name_ISO3=[country_ISO3_code '_' strrep(country_name,' ','')]; % as often used
%
% define the path and filename of the entity file (assets)
% (generated if not exists, stored for subsequent calls)
entity_today_file=[climada_global.entities_dir filesep country_name_ISO3 '_10x10.mat'];
%
% the entity which contains measures and damage functions for bushfire
entity_BF_template=[module_data_dir filesep 'entities' filesep 'Victoria_today_adaptation' climada_global.spreadsheet_ext]; % do NOT change

% define the path and filename of the intermediate step data file
% (generated by bf_generator_jumpy, stored for subsequent calls)
[fP,fN]=fileparts(csv_file);bf_file=[fP filesep fN '_BF_proto_data.mat'];
%bf_file=[module_data_dir filesep 'hazards' filesep 'external_model_output' filesep 'ZAF_BF_proto_data.mat'];

% check for and if needed generate entity
if ~exist(entity_today_file,'file')
    entity_today=climada_entity_country(country_ISO3_code);
else
    entity_today=climada_entity_load(entity_today_file);
end
% load the template entity for bushfire (with measures and damage functions)
entity_BF=climada_entity_read(entity_BF_template,'NOENCODE');
entity_today.damagefunctions=entity_BF.damagefunctions;
entity_today.measures       =entity_BF.measures;
figure;climada_entity_plot(entity_today); % plot entity

% check for and if needed generate intermediate step data file
if ~exist(bf_file,'file')
    [fP,fN]=fileparts(bf_file);
    fprintf('WARNING: %s not found\n',bf_file)
    try
        fprintf('--> be patient, it will be generated from FIRMS data ...\n')
        bf=bf_generator_jumpy(1,3000,1,csv_file);
    catch
        fprintf('-> please locate intermediate step data file %s (run bf_generator_jumpy)\n',fN)
        return
    end
else
    fprintf('loading %s ...\n',bf_file)
    load(bf_file)
end

% Generate Hazard Sets and plot entities

% generate the hazard sets (_ in filename to easily find them)
hazard_today        = climada_bf_hazard_set(bf,entity_today,1.00,'',['_TEST_' country_name_ISO3 '_BF_today']);
hazard_CC_f03       = climada_bf_hazard_set(bf,entity_today,1.03,'',['_TEST_' country_name_ISO3 '_BF_CC_f03']);
hazard_CC_f65       = climada_bf_hazard_set(bf,entity_today,1.65,'',['_TEST_' country_name_ISO3 '_BF_CC_f65']);

% read and encode the entities
entity_today = climada_assets_encode(entity_today,hazard_today);
entity_2030 = entity_today;
entity_2030.assets.Value = entity_today.assets.Value*1.32;
entity_2030.assets.Cover = entity_2030.assets.Value;

if plot_fires
    % Plot fires
    n=length(bf);
    figure
    for i=1:n
        scatter(bf(i).lon,bf(i).lat,30,bf(i).intensity,'filled','s'); colormap hot;
        hold on
    end
    climada_plot_world_borders(2);
    xlim([min(entity_today.assets.lon),max(entity_today.assets.lon)]);
    ylim([min(entity_today.assets.lat),max(entity_today.assets.lat)]);
    xlabel('longitude');ylabel('latitude')
    grid on;legend('simulated fires','location','southeast');drawnow
end

% Please zoom in to see smaller scale structure of the fires.

% Generate Hazard Sets and Risk Plot

% calculate risk today, + ecnomic development, + low/high climate change (CC)
EDS_today       = climada_EDS_calc(entity_today,hazard_today);
EDS_2030        = climada_EDS_calc(entity_2030,hazard_today);
EDS_2030_CC_f03 = climada_EDS_calc(entity_2030,hazard_CC_f03);
EDS_2030_CC_f65 = climada_EDS_calc(entity_2030,hazard_CC_f65);

% plot risk for high and low climate change scenario
figure
subplot(1,3,1);climada_waterfall_graph(EDS_today,EDS_2030,EDS_2030_CC_f03);title('moderate climate change')
subplot(1,3,2);climada_waterfall_graph(EDS_today,EDS_2030,EDS_2030_CC_f65);title('high climate change')

% Adaptation

% establish baseline today
res_today_adapt = climada_measures_impact(entity_today,hazard_today,'no');

% impact of fire fighters
diff_AED_ff  = res_today_adapt.ED(end)-res_today_adapt.ED(1);
% impact of education
diff_AED_edu = res_today_adapt.ED(end)-res_today_adapt.ED(2);
% impact of sprinkler system
diff_AED_sprinkler = res_today_adapt.ED(end)-res_today_adapt.ED(3);

res_2030_adapt_CC_f03 = climada_measures_impact(entity_2030, hazard_CC_f03,res_today_adapt);
res_2030_adapt_CC_f65 = climada_measures_impact(entity_2030, hazard_CC_f65,res_today_adapt);

% for it to work needed to comment out row 324 in
% climada_adaptation_cost_curve.m: clear clear measures_impact_comparison
subplot(1,3,3);climada_adaptation_cost_curve(res_2030_adapt_CC_f03,res_2030_adapt_CC_f65)
